### ISSUE TITLE
RPC won't running if Valorant isn't installed in C drive

### ISSUE THREAD

**Issue by Iqrar99** [colinhartigan/valorant-rpc#105]
I installed my Valorant on my E drive instead of C. The program can't run properly. 

### Error:
```
Traceback (most recent call last):
  File "valclient\client.py", line 907, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Iqrar\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 912, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 50, in __init__
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
press enter to exit...
```

### Suggestion:
It would be good if we can specify the client app location before starting the RPC.

**Comment by Iqrar99** [comment]
Update: I found the solution for this issue for now. **Run the Valorant client first and then run the RPC.** It will work.

But if you want to implement my suggestion, I really appreciate it. You can close my issue if you want.

**Comment by colinhartigan** [comment]
my VALORANT isn't installed on my C drive either

you should be able to launch RPC before the game now
