### ISSUE TITLE
I can't launch it since I have Valorant installed somewhere else

### ISSUE THREAD

**Issue by fauzanbjm** [colinhartigan/valorant-rpc#106]
First time launching, it already gave me error because I have Valorant installed in my D: Drive

attempting to autodetect region
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "valclient\client.py", line 907, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fauzan\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 912, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 50, in __init__
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
press enter to exit...

**Comment by colinhartigan** [comment]
launch VALORANT first
