### ISSUE TITLE
Just downloaded and this happend 

### ISSUE THREAD

**Issue by sondermusik** [colinhartigan/valorant-rpc#107]
Traceback (most recent call last):
  File "src\startup.py", line 56, in __init__
  File "src\presence\presence.py", line 27, in __init__
  File "pypresence\presence.py", line 45, in connect
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "pypresence\baseclient.py", line 113, in handshake
  File "asyncio\windows_events.py", line 313, in create_pipe_connection
  File "asyncio\windows_events.py", line 584, in connect_pipe
PermissionError: [WinError 5] Zugriff verweigert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>

**Comment by colinhartigan** [comment]
try running as administrator
