### ISSUE TITLE
Issue with starting VALORANT

### ISSUE THREAD

**Issue by Flixl09** [colinhartigan/valorant-rpc#114]
`Traceback (most recent call last):
  File "valclient\client.py", line 907, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 912, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 50, in __init__
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
Drücken Sie enter zum Schließen`

I cut out my name in the path but what should i do

**Comment by Flixl09** [comment]
Nvm it worked
