### ISSUE TITLE
Program throws an error after quitting VALORANT

### ISSUE THREAD

**Issue by caulmseh** [colinhartigan/valorant-rpc#115]
`Traceback (most recent call last):
  File "urllib3\connection.py", line 175, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 710, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 187, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000019856628D08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 450, in send
  File "urllib3\connectionpool.py", line 786, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=50902): Max retries exceeded with url: /chat/v4/presences (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019856628D08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\presence\presence.py", line 80, in init_loop
  File "src\presence\presence.py", line 54, in main_loop
  File "valclient\client.py", line 751, in fetch_presence
  File "valclient\client.py", line 114, in fetch
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=50902): Max retries exceeded with url: /chat/v4/presences (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019856628D08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
press enter to exit...`

**Comment by zayKenyon** [comment]
The error isn't pretty, but it's intentional. How would it work if VALORANT was closed?

**Comment by EMREOYUN** [comment]
> The error isn't pretty, but it's intentional. How would it work if VALORANT was closed?

Where is the feature that opens the game if the game itself is closed, may I ask?
