### ISSUE TITLE
Attempting to autodetect region

### ISSUE THREAD

**Issue by notfebri** [colinhartigan/valorant-rpc#116]
attempting to autodetect region
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "valclient\client.py", line 907, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 912, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 50, in __init__
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
press enter to exit...

**Comment by NimaWoods** [comment]
Same here

**Comment by notfebri** [comment]
> Same here

open the valorant game if you have entered the main menu then minimize it, after that install valorant rpc and work, that's what I did to solve the problem
