### ISSUE TITLE
RPC stops working after playing for about 20 mins

### ISSUE THREAD

**Issue by EllairaX** [colinhartigan/valorant-rpc#121]
I have Valorant installed in my D drive and I typically start Valorant using RPC. RPC will work at first, but then after about 15-20 minutes it stops working.

**Comment by EllairaX** [comment]
I was able to catch the error:

`_   _____   __   ____  ___  ___   _  ________
| | / / _ | / /  / __ \/ _ \/ _ | / |/ /_  __/__________  ____
| |/ / __ |/ /__/ /_/ / , _/ __ |/    / / / /___/ __/ _ \/ __/
|___/_/ |_/____/\____/_/|_/_/ |_/_/|_/ /_/     /_/ / .__/\__/
                                                  /_/ v3.2.1

starting VALORANT

Exception in thread Thread-1:
Traceback (most recent call last):
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "http\client.py", line 1422, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "src\utilities\systray.py", line 26, in run
  File "src\utilities\systray.py", line 51, in generate_icon
  File "urllib\request.py", line 247, in urlretrieve
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
[59] waiting for presence...
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 66, in __init__
  File "src\startup.py", line 82, in run
  File "src\startup.py", line 127, in wait_for_presence
  File "src\utilities\systray.py", line 39, in exit
AttributeError: 'Systray' object has no attribute 'systray'
press enter to exit...
`

When I launch Valorant first and then open RPC, it seems to work okay. Update: Sometimes this doesn't work either.
