### ISSUE TITLE
Others region support

### ISSUE THREAD

**Issue by Cr1stalz** [colinhartigan/valorant-rpc#13]
How soon we can use this programm on others region?

**Comment by colinhartigan** [comment]
pretty busy with school stuff, so a few weeks at most

**Comment by deva0000** [comment]
Whats the problem with regions? Im from BR and I can use no problems

**Comment by colinhartigan** [comment]
the endpoints for getting live match data are different in different regions (only used in v2.0+)

check which shard you're on?
![image](https://user-images.githubusercontent.com/42125428/112887689-7a3ec300-90a1-11eb-9a68-f9a2aea6519e.png)

**Comment by deva0000** [comment]
![image](https://user-images.githubusercontent.com/80850739/112888016-3ac8a480-90aa-11eb-99dc-b49717b8e6b7.png)

**Comment by Cr1stalz** [comment]
![image](https://user-images.githubusercontent.com/43808665/112915454-e288b580-9130-11eb-94dc-d11404bc369b.png)

**Comment by colinhartigan** [comment]
added in [release v2.2](https://github.com/colinhartigan/valorant-rpc/releases/tag/v2.2)

**Comment by Bygrilinho** [comment]
Seems like BR still doesn't work
```
 _    _____    __    ____  ____  ___    _   ________            ____  ____  ______
| |  / /   |  / /   / __ \/ __ \/   |  / | / /_  __/           / __ \/ __ \/ ____/
| | / / /| | / /   / / / / /_/ / /| | /  |/ / / /    ______   / /_/ / /_/ / /
| |/ / ___ |/ /___/ /_/ / _, _/ ___ |/ /|  / / /    /_____/  / _, _/ ____/ /___
|___/_/  |_/_____/\____/_/ |_/_/  |_/_/ |_/ /_/             /_/ |_/_/    \____/                                         

https://github.com/colinhartigan/valorant-rpc


 * Running on http://127.0.0.1:6969/ (Press CTRL+C to quit)
[i] initializing systray object
[i] systray ready!
[i] valorant not opened, attempting to run...
[i] presence detected! hiding window...
[i] starting loop

[!] exception:
Traceback (most recent call last):
  File "urllib3\connection.py", line 159, in _new_conn
  File "urllib3\util\connection.py", line 61, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 309, in connect
  File "urllib3\connection.py", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x04AE0040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='glz-br-1.br.a.pvp.net', port=443): Max retries exceeded with url: /pregame/v1/players/d8fb38b9-75f0-51f2-a502-5af2b1ea6b3b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04AE0040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valorantrpc\main.py", line 218, in listen
  File "valorantrpc\main.py", line 158, in update_rpc
  File "valorantrpc\match_session.py", line 27, in init_pregame
  File "valorantrpc\client_api.py", line 13, in get_glz
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='glz-br-1.br.a.pvp.net', port=443): Max retries exceeded with url: /pregame/v1/players/d8fb38b9-75f0-51f2-a502-5af2b1ea6b3b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04AE0040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by colinhartigan** [comment]
try EU

**Comment by Bygrilinho** [comment]
MatchID error
```
 _    _____    __    ____  ____  ___    _   ________            ____  ____  ______
| |  / /   |  / /   / __ \/ __ \/   |  / | / /_  __/           / __ \/ __ \/ ____/
| | / / /| | / /   / / / / /_/ / /| | /  |/ / / /    ______   / /_/ / /_/ / /
| |/ / ___ |/ /___/ /_/ / _, _/ ___ |/ /|  / / /    /_____/  / _, _/ ____/ /___
|___/_/  |_/_____/\____/_/ |_/_/  |_/_/ |_/ /_/             /_/ |_/_/    \____/

https://github.com/colinhartigan/valorant-rpc


 * Running on http://127.0.0.1:6969/ (Press CTRL+C to quit)
[i] initializing systray object
[i] systray ready!
[i] valorant already running!
[i] presence detected! hiding window...
[i] starting loop

[!] exception:
Traceback (most recent call last):
  File "valorantrpc\main.py", line 218, in listen
  File "valorantrpc\main.py", line 158, in update_rpc
  File "valorantrpc\match_session.py", line 28, in init_pregame
KeyError: 'MatchID'
```

**Comment by Bygrilinho** [comment]
I found something in Valorant logs that could help
Looks like it's using `https://glz-br-1.na.a.pvp.net/` and `https://pd.na.a.pvp.net/` for the endpoints

**Comment by colinhartigan** [comment]
oh you're exactly right, i completely forgot there's differences between shards/regions

will fix this soon

**Comment by colinhartigan** [comment]
will be fixed with v3
