### ISSUE TITLE
Error while starting valorant-rpc

### ISSUE THREAD

**Issue by BennyExtreme** [colinhartigan/valorant-rpc#134]
When I start the program this error is returned:
```python
Traceback (most recent call last):
  File "src\presence\presence.py", line 69, in init_loop
  File "src\content\content_loader.py", line 54, in load_all_content
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dannn2k** [comment]
+1, after updating tho

**Comment by BennyExtreme** [comment]
Error in GET `https://shared.<region>.a.pvp.net/content-service/v3/content`
`X-Riot-ClientVersion` header seems to be the problem.
The value `release-06.01-shipping-1-815441` returns error.
```json
{
    "httpStatus": 500,
    "errorCode": "INTERNAL_SERVER_ERROR",
    "message": "Internal error encountered"
}
```
Using `release-06.00-8-814611` works fine.

**Comment by dannn2k** [comment]
tf, where is this located

**Comment by BennyExtreme** [comment]
## EU account
Using GET `https://glz-<region>-1.<region>.a.pvp.net/session/v1/sessions/<puuid>` endpoint on my EU account gives in the response `"clientVersion": "release-06.00-shipping-8-814611"` that is a valid value for the `X-Riot-ClientVersion`.
If i login with this account and check the log at `%LOCALAPPDATA%\VALORANT\Saved\Logs\ShooterGame.log`
it shows
```
[2023.01.18-22.43.05:821][  0]LogShooter: Display: CI server version: release-06.00-8-814611
[2023.01.18-22.43.05:821][  0]LogShooter: Display: Branch: release-06.00
[2023.01.18-22.43.05:821][  0]LogShooter: Display: Changelist: 814611
[2023.01.18-22.43.05:821][  0]LogShooter: Display: Build version: 8
```
again, `release-06.00-8-814611` is a valid value for the `X-Riot-ClientVersion`.

## NA account
Using GET `https://glz-<region>-1.<region>.a.pvp.net/session/v1/sessions/<puuid>` on my NA account gives in the response `"clientVersion": "release-06.01-shipping-3-815441"` that is a valid value for the `X-Riot-ClientVersion`.
If i login with this account and check the log at `%LOCALAPPDATA%\VALORANT\Saved\Logs\ShooterGame.log`
it shows
```
[2023.01.18-22.54.15:323][  0]LogShooter: Display: CI server version: release-06.01-3-815441
[2023.01.18-22.54.15:323][  0]LogShooter: Display: Branch: release-06.01
[2023.01.18-22.54.15:323][  0]LogShooter: Display: Changelist: 815441
[2023.01.18-22.54.15:323][  0]LogShooter: Display: Build version: 3
```
again, `release-06.01-3-815441` is a valid value for the `X-Riot-ClientVersion`

---
It seems at this point that the version returned by https://valorant-api.com/v1/version does not exist...
I mean, the correct build is not version 1 but version 3.

The problem has been forwarded to valorant-api.com developer.

Personally I would have avoided [using valorant-api.com as a "dependency" to know the client version](https://github.com/colinhartigan/valclient.py/blob/05f0dd5c9f99e6406efd55eda7aa31d40fd4fc42/src/valclient/client.py#L1106).

**Comment by BennyExtreme** [comment]
Fixed by valorant-api.com developer.
