### ISSUE TITLE
Error when using the RPC - Not launching the game even as Admin

### ISSUE THREAD

**Issue by Toracles** [colinhartigan/valorant-rpc#137]
Traceback (most recent call last):
  File "urllib3\connection.py", line 175, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 710, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 187, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C4EBE18E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 450, in send
  File "urllib3\connectionpool.py", line 786, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=60731): Max retries exceeded with url: /chat/v4/presences (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBE18E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 66, in __init__
  File "src\startup.py", line 82, in run
  File "src\startup.py", line 122, in wait_for_presence
  File "valclient\client.py", line 751, in fetch_presence
  File "valclient\client.py", line 114, in fetch
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=60731): Max retries exceeded with url: /chat/v4/presences (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBE18E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by eyepatch010** [comment]
Where do you check the errors btw just curious
