### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by brxndonnn** [colinhartigan/valorant-rpc#146]
starting VALORANT
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 66, in __init__
  File "src\startup.py", line 74, in run
  File "src\startup.py", line 138, in start_game
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
OSError: [WinError 740] The requested operation requires elevation
press enter to exit...

**Comment by didotb** [comment]
As stated on line 10
> OSError: [WinError 740] The requested operation requires elevation

Try running as admin
