### ISSUE TITLE
Add support for Discord canary and PtB

### ISSUE THREAD

**Issue by Czekoloczek** [colinhartigan/valorant-rpc#149]
If you ran valorant-rpc with Discord canary open it throws this error

```czekanie na rpc client
Traceback (most recent call last):
  File "src\startup.py", line 56, in __init__
  File "src\presence\presence.py", line 26, in __init__
  File "pypresence\presence.py", line 13, in __init__
  File "pypresence\baseclient.py", line 28, in __init__
pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
discord został nie wykryty! włączanie gry bez presence... (Could not find Discord installed and running on this machine.)
program napotkał błąd: proszę utworzyć problem z poniższym śledzeniem, jeśli problem będzie się powtarzał
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 66, in __init__
  File "src\startup.py", line 70, in run
AttributeError: 'Startup' object has no attribute 'presence'
wciśnij enter aby wyjść...```

**Comment by didotb** [comment]
As of [v3.2.3](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.2.3), it is being detected normally on `canary 294386 (0050500) Host 1.0.254 x86 (47989) Windows 10 64-bit (10.0.19045)`. Is your discord installation in the default install location? Did you perhaps modify the files at AppData, or used a plugin that did so?
