### ISSUE TITLE
Program encountered an error?

### ISSUE THREAD

**Issue by coldxsin** [colinhartigan/valorant-rpc#47]
Traceback (most recent call last):
  File "valclient\client.py", line 822, in __get_headers
KeyError: 'subject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 70, in activate
  File "valclient\client.py", line 838, in __get_headers
Exception: Unable to get headers; is VALORANT running?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "src\startup.py", line 34, in __init__
  File "src\startup.py", line 132, in check_region
  File "valclient\client.py", line 78, in activate
Exception: Unable to activate; is VALORANT running?
press enter to exit...

**Comment by coldxsin** [comment]
my valorant is closed although the program says its still running? is there a fix for this?

**Comment by rxri** [comment]
@coldxsin, your VALORANT isn't running and program literally says `is VALORANT running?`. It's a question here. Program doesn't say anywhere that it's running ( ❓ ). There is nothing to fix.

**Comment by coldxsin** [comment]
oh...
