### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Glaived** [colinhartigan/valorant-rpc#49]
```
Traceback (most recent call last):
File "src\presence\presence.py", line 33, in main_loop
File "src\presence\presence.py", line 56, in update_presence
File "src\presence\presences\pregame.py", line 33, in presence
File "pypresence\presence.py", line 34, in update
File "asyncio\base_events.py", line 579, in run_until_complete
File "pypresence\baseclient.py", line 109, in read_output
pypresence.exceptions.ServerError: Child "activity" fails because child "party" fails because child "size" fails because "size" at position 1 fails because "1" must be larger than or equal to 1
press enter to exit...
```

¯\_(ツ)_/¯

**Comment by colinhartigan** [comment]
resolved in [v3.1.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.1.0)
