### ISSUE TITLE
Error opening/using valorant-rpc.exe

### ISSUE THREAD

**Issue by jamiejcole** [colinhartigan/valorant-rpc#60]
Downloaded [v3.0.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.0.0) and ran for the first time, threw this error:

```
attempting to autodetect region
the program encountered an error; please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "valclient\client.py", line 848, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xyz\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 69, in activate
  File "valclient\client.py", line 853, in __get_lockfile
Exception: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "src\startup.py", line 34, in __init__
  File "src\startup.py", line 132, in check_region
  File "valclient\client.py", line 78, in activate
Exception: Unable to activate; is VALORANT running?
press enter to exit...
```

This file doesn't exist in the path:
![image](https://user-images.githubusercontent.com/48195376/130704373-229eea4a-a8c7-4fec-9529-8197083f8246.png)

**Comment by janinhasz** [comment]
tried running as admin and already in the game lobby?

**Comment by zayKenyon** [comment]
You need to be in a VALORANT game for it to work.

Also ValClient isn't the VALORANT client,  that is a package maintained by Colin.
