### ISSUE TITLE
error that happens every so often

### ISSUE THREAD

**Issue by PangwenE** [colinhartigan/valorant-rpc#69]
```
 _   _____   __   ____  ___  ___   _  ________
| | / / _ | / /  / __ \/ _ \/ _ | / |/ /_  __/__________  ____
| |/ / __ |/ /__/ /_/ / , _/ __ |/    / / / /___/ __/ _ \/ __/
|___/_/ |_/____/\____/_/|_/_/ |_/_/|_/ /_/     /_/ / .__/\__/
                                                  /_/ v3.1.0

program startup successful, hiding window in 5 seconds

presence running!
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "src\presence\presence.py", line 35, in main_loop
  File "src\presence\presence.py", line 65, in update_presence
  File "src\presence\presences\pregame.py", line 9, in presence
  File "valclient\client.py", line 599, in pregame_fetch_player
  File "valclient\client.py", line 101, in fetch
  File "valclient\client.py", line 93, in __verify_status_code
valclient.exceptions.PhaseError: You are not in a pre-game
press enter to exit...
```

**Comment by PangwenE** [comment]
note: i do have WAIUA (who am i up against), that might be interfering

**Comment by colinhartigan** [comment]
a few people are still encountering this bug... i thought i fixed it but i guess not, i'll look into it further

**Comment by colinhartigan** [comment]
fixed
