### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by igl-nigal** [colinhartigan/valorant-rpc#75]
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 445, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 440, in _make_request
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 306, in begin
  File "http\client.py", line 275, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 532, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 445, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 440, in _make_request
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 306, in begin
  File "http\client.py", line 275, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 66, in __init__
  File "src\startup.py", line 82, in run
  File "src\startup.py", line 122, in wait_for_presence
  File "valclient\client.py", line 733, in fetch_presence
  File "valclient\client.py", line 113, in fetch
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by colinhartigan** [comment]
sometimes this error shows up when you close valorant but you can just ignore it
