### ISSUE TITLE
error while Valorant is running in the background

### ISSUE THREAD

**Issue by Dreamtrailtv** [colinhartigan/valorant-rpc#80]
Traceback (most recent call last):
  File "pypresence\baseclient.py", line 102, in read_output
  File "asyncio\streams.py", line 621, in read
  File "asyncio\proactor_events.py", line 370, in _loop_writing
  File "asyncio\windows_events.py", line 474, in send
BrokenPipeError: [WinError 232] Die Pipe wird gerade geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\presence\presence.py", line 35, in main_loop
  File "src\presence\presence.py", line 65, in update_presence
  File "src\presence\presences\menu.py", line 10, in presence
  File "src\presence\presences\menu_presences\default.py", line 9, in presence
  File "src\presence\presences\menu_presences\away.py", line 10, in presence
  File "pypresence\presence.py", line 34, in update
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "pypresence\baseclient.py", line 106, in read_output
pypresence.exceptions.InvalidID: Client ID is Invalid

![image](https://user-images.githubusercontent.com/51512219/139417143-5dcc6f3c-3c7f-4c83-8919-754c9d719b81.png)

**Comment by rxri** [comment]
ClientID of presence is invalid, try deleting config from `%appdata%/valorant-rpc` and try launching valorant-rpc again

**Comment by colinhartigan** [comment]
looks like a pypresence error - make sure discord is open

**Comment by zayKenyon** [comment]
Do you still get this error with newer RPC versions?
