### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by Mahdi8186** [colinhartigan/valorant-rpc#90]
I only used this program a few times and it worked fine, but now I get this error
both valorant and dicord are open
How can I fix it?

v3.1.4

the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 32, in __init__
  File "src\utilities\program_data.py", line 22, in update_file_location
  File "src\utilities\program_data.py", line 36, in modify_isntalls
PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\valorant-tools\\installs.json'
press enter to exit...

**Comment by colinhartigan** [comment]
run as admin
