### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Domme678** [colinhartigan/valorant-rpc#95]
Traceback (most recent call last):
  File "valclient\client.py", line 889, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\domme\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 894, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 50, in __init__
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?

**Comment by shimizu-izumi** [comment]
Start the game then start the RPC that will fix it because the lockfile is created when you start Valorant

**Comment by colinhartigan** [comment]
like @LeonHenning said, run the game first
