### ISSUE TITLE
no longer working on my laptop

### ISSUE THREAD

**Issue by josephosphorus** [colinhartigan/valorant-rpc#97]
as the title suggests, I was using this program for 2 weeks starting from mid to late December and it worked just fine, but over the past few days it has been on a stalemate and only saying

starting VALORANT
Expecting value: line 1 column 1 (char 0)
attempting to autodetect region
Expecting value: line 1 column 1 (char 0)
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "valclient\client.py", line 851, in __get_headers
  File "valclient\client.py", line 878, in __get_auth_headers
  File "valclient\client.py", line 884, in __get_current_version
  File "requests\models.py", line 910, in json
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 74, in activate
  File "valclient\client.py", line 859, in __get_headers
valclient.exceptions.HandshakeError: Unable to get headers; is VALORANT running?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 66, in __init__
  File "src\startup.py", line 76, in run
  File "src\startup.py", line 116, in setup_client
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
press enter to exit...

I didn't even make any changes to my laptop nor the program and the game itself so why is this happening? Tried downloading the same .exe that was issued on 4th of November to no avail.

**Comment by colinhartigan** [comment]
is valorant running?
